# inference_config 
inference_config:
  # decoding results are stored in ${checkpoint_path}/../decode/${infer_dirname_tag}
  inference_dirname_tag: debug 
  test_list: &test_list data/librispeech/datalist/dev-other.jsonl

# data config
data_config: 
  epoch: 1
  start_epoch: 0
  num_workers: 9 #18
  shuffle: False
  keyword_selection_conf:
    selection_strategy: random_sample
    config:
      positive_prob: 0.5 # 50% positive, 50% negative for KWS eval
      # sample_config is useless in fixed keyword evaluation.
      sample_config: 
        keyword_length_range: [2,6]
        continuous: True
      special_token: 
        sok: 5002
        eok: 5003
        unk: 1
        psok: 71
        peok: 72
        punk: 73
        with_trans: True
      use_filler_label_for_neg: False

  predefined_keyword_config:
    train:
      kwd2uttids_jsonl: data/kwd2uttids_jsonl/dev-other.jsonl
      pick_predefined_prob: 0 #! When we do fixed keyword evaluation, this prob must be set to 0.
  
  length_key: mixspeech,speech,keyword
  fetch_key:  speech,speech_len,phn_label,phn_label_len,keyword,keyword_len,target
  fetch_meta_key: key,match_case,keyword,phn_label_list,text,sph,corruption_material,num_corrupt
  batch_size: 64
  test_list: *test_list
  




