dataloader_args:
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  prefetch_factor: 4

dataset_args:
  resample_rate: 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 48000

enable_amp: false
exp_dir: exp/DPCNN
gpus: '0,1'
log_batch_interval: 100

loss: SISDR
loss_args: { }

model:
  tse_model: DPCCN
model_args:
  tse_model:
    win: 512
    stride: 128
    feature_dim: 257
    tcn_blocks: 10
    tcn_layers: 2
    spk_emb_dim: 256
    causal: False
    spk_fuse_type: 'multiply'
    use_spk_transform: False
    joint_training: False

model_init:
  tse_model: null
  discriminator: null
num_avg: 5
num_epochs: 150

optimizer:
  tse_model: Adam
optimizer_args:
  tse_model:
    lr: 0.001
    weight_decay: 0.0001

clip_grad: 3.0
save_epoch_interval: 1

scheduler:
  tse_model: ExponentialDecrease
scheduler_args:
  tse_model:
    final_lr: 2.5e-05
    initial_lr: 0.001
    warm_from_zero: false
    warm_up_epoch: 0

seed: 42
