dataloader_args:
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  prefetch_factor: 4

dataset_args:
  resample_rate: 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 16000

enable_amp: false
exp_dir: exp/TFGridNet
gpus: '0,1'
log_batch_interval: 100

loss: SI_SNR
loss_args: { }

model:
  tse_model: TFGridNet
model_args:
  tse_model:
    n_srcs: 1
    n_fft: 128
    stride: 64
    window: "hann"
    n_imics: 1
    n_layers: 6
    lstm_hidden_units: 192
    attn_n_head: 4
    attn_approx_qk_dim: 512
    emb_dim: 128
    emb_ks: 1
    emb_hs: 1
    activation: "prelu"
    eps: 1.0e-5
    spk_emb_dim: 256
    use_spk_transform: False
    spk_fuse_type: "multiply"
    joint_training: False


model_init:
  tse_model: null
num_avg: 2
num_epochs: 150

optimizer:
  tse_model: Adam
optimizer_args:
  tse_model:
    lr: 0.001
    weight_decay: 0.0001

clip_grad: 5.0
save_epoch_interval: 1

scheduler:
  tse_model: ExponentialDecrease
scheduler_args:
  tse_model:
    final_lr: 2.5e-05
    initial_lr: 0.001
    warm_from_zero: false
    warm_up_epoch: 0

seed: 42
